apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: {{ include "aws-default-addons.fullname" . }}-jenkins
  labels:
    {{- include "aws-default-addons.labels" . | nindent 4 }}
spec:
  rollbackLimit: 3
  forProvider:
    chart:
      name: jenkins
      repository: https://charts.jenkins.io
      version: 3.5.17
    namespace: jenkins
#   skipCreateNamespace: true
#   wait: true
    values:
      controller:
        tag: "2.312-jdk11"
        adminUser: "admin"
        adminPassword: "admindemo"
        ingress:
          enabled: false
          apiVersion: "networking.k8s.io/v1"
          ingressClassName: nginx
          hostName: jenkins.{{ .Values.domain }}
      persistence:
        enabled: true
        storageClass: gp2
    set: []
    valuesFrom: []
  providerConfigRef:
    name: {{ include "aws-default-addons.fullname" . }}