apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: {{ include "aws-default-addons.fullname" . }}-ebs-csi
  labels:
    {{- include "aws-default-addons.labels" . | nindent 4 }}
spec:
  rollbackLimit: 3
  forProvider:
    chart:
      name: aws-ebs-csi-driver
      repository: https://kubernetes-sigs.github.io/aws-ebs-csi-driver
      version: 2.1.0
    namespace: kube-system
#   skipCreateNamespace: true
#   wait: true
    values: 
      controller:
        region: {{ .Values.region }}
        serviceAccount:
          annotations: 
            eks.amazonaws.com/role-arn: "arn:aws:iam::{{ .Values.accountID }}:role/{{ include "aws-default-addons.fullname" . }}-ebs-csi"
      node:
        tolerateAllTaints: true
        serviceAccount:
          annotations: 
            eks.amazonaws.com/role-arn: "arn:aws:iam::{{ .Values.accountID }}:role/{{ include "aws-default-addons.fullname" . }}-ebs-csi"
      storageClasses:
      {{ range .Values.ebs }}
        - name: {{ .name }}
          provisioner: ebs.csi.aws.com
          {{ with .parameters }}
          parameters:
          {{ toYaml . | nindent 12 }}
          {{ end }}
          volumeBindingMode: WaitForFirstConsumer
          allowVolumeExpansion: true
      {{ end }}
    set: []
    valuesFrom: []
  providerConfigRef:
    name: {{ include "aws-default-addons.fullname" . }}