apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: {{ include "aws-default-addons.fullname" . }}-prometheus-stack
  labels:
    {{- include "aws-default-addons.labels" . | nindent 4 }}
spec:
  rollbackLimit: 3
  forProvider:
    chart:
      name: kube-prometheus-stack
      repository: https://prometheus-community.github.io/helm-charts
      version: 18.0.12
    namespace: monitoring
#   skipCreateNamespace: true
#   wait: true
    values: 
      alertmanager:
        ingress:
          enabled: true
          hosts: 
          - alertmanager.{{ .Values.domain }}
          ingressClassName: nginx
          pathType: ImplementationSpecific
        #   annotations: {}
      grafana:
        adminPassword: admindemo
        ingress:
          enabled: true
          annotations: 
            kubernetes.io/ingress.class: nginx
          hosts:
          - grafana.{{ .Values.domain }}
      prometheus:
        thanosIngress:
          enabled: true
          ingressClassName: nginx
        #   annotations: {}
          hosts: 
          - thanos-gateway.{{ .Values.domain }}
          paths: 
          - /
          pathType: ImplementationSpecific
        ingress:
          enabled: true
          ingressClassName: nginx
        #   annotations: {}
          hosts:
          - prometheus.{{ .Values.domain }}
          pathType: ImplementationSpecific
    set: []
    valuesFrom: []
  providerConfigRef:
    name: {{ include "aws-default-addons.fullname" . }}