apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: {{ include "aws-default-addons.fullname" . }}-litmus
  labels:
    {{- include "aws-default-addons.labels" . | nindent 4 }}
spec:
  rollbackLimit: 3
  forProvider:
    chart:
      name: litmus
      repository: https://litmuschaos.github.io/litmus-helm/
      version: 2.1.1
    namespace: litmus
#   skipCreateNamespace: true
#   wait: true
    values: 
      ingress:
        enabled: true
        name: litmus-ingress
        annotations:
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/rewrite-target: /$1
        host:
          name: "litmus.{{ .Values.domain }}"
          paths:
            frontend: /(.*)
            backend: /backend/(.*)
      portal:
        server:
          authServer:
            env:
              ADMIN_USERNAME: "admin"
              ADMIN_PASSWORD: "admindemo"
    set: []
    valuesFrom: []
  providerConfigRef:
    name: {{ include "aws-default-addons.fullname" . }}