apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: {{ include "aws-default-addons.fullname" . }}-ingress-nginx
  labels:
    {{- include "aws-default-addons.labels" . | nindent 4 }}
spec:
  rollbackLimit: 3
  forProvider:
    chart:
      name: ingress-nginx
      repository: https://kubernetes.github.io/ingress-nginx
      version: 4.0.1
    namespace: ingress-nginx
#   skipCreateNamespace: true
#   wait: true
    values:
      controller:
        service:
          annotations: 
            service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
            service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
            service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
            service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
            external-dns.alpha.kubernetes.io/hostname: {{ .Values.domain }}.
        metrics:
          port: 10254
          # if this port is changed, change healthz-port: in extraArgs: accordingly
          enabled: true

          service:
            annotations: 
              prometheus.io/scrape: "true"
              prometheus.io/port: "10254"
          serviceMonitor:
            enabled: true
            namespace: "monitoring"
    set: []
    valuesFrom: []
  providerConfigRef:
    name: {{ include "aws-default-addons.fullname" . }}


