apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: {{ include "aws-default-addons.fullname" . }}-rook-operator
  labels:
    {{- include "aws-default-addons.labels" . | nindent 4 }}
spec:
  rollbackLimit: 3
  forProvider:
    chart:
      name: rook-ceph
      repository: https://charts.rook.io/release
      version: v1.7.4
    namespace: rook-ceph
#   skipCreateNamespace: true
#   wait: true
    values: {}
    set: []
    valuesFrom: []
  providerConfigRef:
    name: {{ include "aws-default-addons.fullname" . }}
---
apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: {{ include "aws-default-addons.fullname" . }}-rook
  labels:
    {{- include "aws-default-addons.labels" . | nindent 4 }}
spec:
  rollbackLimit: 3
  forProvider:
    chart:
      name: rook-ceph-cluster
      repository: https://charts.rook.io/release
      version: v1.7.4
    namespace: rook-ceph
#   skipCreateNamespace: true
#   wait: true
    values:
      monitoring:
        enabled: true
      toolbox:
        enabled: true
      ingress:
        dashboard: 
          annotations:
            kubernetes.io/ingress.class: nginx
            nginx.ingress.kubernetes.io/rewrite-target: /$2
          host:
            name: ceph-dashboard.{{ .Values.domain }}
            path: "/(/|$)(.*)"
      cephBlockPools: []
      cephFileSystems:
        - name: ceph-filesystem
          spec:
            metadataPool:
              replicated:
                size: 1
            dataPools:
              - replicated:
                  size: 1
            metadataServer:
              activeCount: 1
              activeStandby: true
          storageClass:
            enabled: true
            isDefault: false
            name: ceph-filesystem
            reclaimPolicy: Delete
            allowVolumeExpansion: true
            provisioner: rook-ceph.cephfs.csi.ceph.com
            parameters:
              csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
              csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
              csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
              csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
              csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
              csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
              csi.storage.k8s.io/fstype: ext4
      cephObjectStores: []
      cephClusterSpec:
        mon:
          count: 1
          allowMultiplePerNode: true
          volumeClaimTemplate:
            spec:
              storageClassName: gp2
              resources:
                requests:
                  storage: 30Gi
        dashboard:
          enabled: true
          urlPrefix: /
        storage:
          storageClassDeviceSets:
          - name: set1
            count: 1
            portable: true
            tuneDeviceClass: true
            tuneFastDeviceClass: false
            encrypted: false
            placement:
              topologySpreadConstraints:
              - maxSkew: 1
                topologyKey: kubernetes.io/hostname
                whenUnsatisfiable: ScheduleAnyway
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - rook-ceph-osd
            preparePlacement:
              podAntiAffinity:
                preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  podAffinityTerm:
                    labelSelector:
                      matchExpressions:
                      - key: app
                        operator: In
                        values:
                        - rook-ceph-osd
                      - key: app
                        operator: In
                        values:
                        - rook-ceph-osd-prepare
                    topologyKey: kubernetes.io/hostname
              topologySpreadConstraints:
              - maxSkew: 1
                topologyKey: topology.kubernetes.io/zone
                whenUnsatisfiable: ScheduleAnyway
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - rook-ceph-osd-prepare
            volumeClaimTemplates:
            - metadata:
                name: data
              spec:
                resources:
                  requests:
                    storage: 30Gi
                storageClassName: gp2
                volumeMode: Block
                accessModes:
                  - ReadWriteOnce          
    set: []
    valuesFrom: []
  providerConfigRef:
    name: {{ include "aws-default-addons.fullname" . }}


