apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: {{ include "aws-default-addons.fullname" . }}-external-dns
  labels:
    {{- include "aws-default-addons.labels" . | nindent 4 }}
spec:
  rollbackLimit: 3
  forProvider:
    chart:
      name: external-dns
      repository: https://kubernetes-sigs.github.io/external-dns
      version: 1.2.0
    namespace: external-dns
#   skipCreateNamespace: true
#   wait: true
    values:
      serviceAccount:
        annotations: 
          eks.amazonaws.com/role-arn: "arn:aws:iam::{{ .Values.accountID }}:role/{{ include "aws-default-addons.fullname" . }}-external-dns"
      podAnnotations:
        eks.amazonaws.com/role-arn: "arn:aws:iam::{{ .Values.accountID }}:role/{{ include "aws-default-addons.fullname" . }}-external-dns"
      domainFilters: [ "{{ .Values.domain }}" ]
      txtOwnerId: "{{ .Values.environmentName }}"
      serviceMonitor:
        enabled: true
    set: []
    valuesFrom: []
  providerConfigRef:
    name: {{ include "aws-default-addons.fullname" . }}
