apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: {{ include "aws-default-addons.fullname" . }}-jenkins
  labels:
    {{- include "aws-default-addons.labels" . | nindent 4 }}
spec:
  rollbackLimit: 3
  forProvider:
    chart:
      name: jenkins
      repository: https://charts.jenkins.io
      version: 3.5.17
    namespace: jenkins
#   skipCreateNamespace: true
#   wait: true
    values:
      controller:
        tag: "2.314-jdk11"
        adminUser: "admin"
        adminPassword: "admindemo"
        containerEnv:
        - name: AWS_REGION
          value: "{{ .Values.region }}"
        - name: ECR_ROLE
          value: "{{ include "aws-default-addons.fullname" . }}-pipeline-ecr"
        ingress:
          enabled: true
          annotations:
            nginx.ingress.kubernetes.io/rewrite-target: /
          apiVersion: "networking.k8s.io/v1"
          ingressClassName: nginx
          hostName: jenkins.{{ .Values.domain }}
        installPlugins:
        - kubernetes:1.30.1
        - kubernetes-cli:1.10.3
        - workflow-aggregator:2.6
        - git:4.8.2
        - configuration-as-code:1.53
        - command-launcher:1.6
        - docker-workflow:1.26
        - job-dsl:1.77
        - pipeline-utility-steps:2.10.0
        - blueocean:1.25.0
        - simple-theme-plugin:0.7
        - prometheus:2.0.10
        - aws-credentials:1.30
        scriptApproval: []
        JCasC:
          defaultConfig: true
          configScripts: 
            welcome-message: |
              jenkins:
                systemMessage: Welcome to {{ .Values.environmentName }} CI\CD server.  This Jenkins is configured and managed 'as code'.
            configuration: |-
              jobs:
                - script: >
                    pipelineJob('app-sample') {
                      definition {
                        cps {
                          script("""\
                            @Library (['core','assembler']) _
                            properties([
                                parameters(
                                    [ string(name: 'REPO_BRANCH', defaultValue: 'main', description: 'git repository branch') ]
                                )
                            ])
                            params.each { k, v -> env[k] = v }
                            env.REPO_URL = "https://github.com/njguilhem2/crud-java.git"
                            env.TECH_TYPE= "java"
                            env.KUBE_NAMESPACE = "default"
                            env.HELM_RELEASE_NAME = "crud-java"
                            env.HELM_CHART_NAME = "chart"
                            env.DOCKER_IMAGE = "crud-java"
                            env.CI_IMAGE = "gradle:7.2.0-jdk11"
                            
                            
                            coreLibrary{}
                          """.stripIndent())
                        }
                      }
                    }
              unclassified:
                globalLibraries:
                  libraries:
                    - name: "assembler"
                      defaultVersion: "orange"
                      retriever:
                        modernSCM:
                          scm:
                            git:
                              remote: "https://github.com/febarbosa182/pipeline-assembler.git"
                    - name: "core"
                      defaultVersion: "orange"
                      retriever:
                        modernSCM:
                          scm:
                            git:
                              remote: "https://github.com/febarbosa182/pipeline-core.git"
                simple-theme-plugin:
                  elements:
                    - cssUrl:
                        url: "https://cdn.rawgit.com/afonsof/jenkins-material-theme/gh-pages/dist/material-deep-orange.css"  
        prometheus:
            enabled: true
      persistence:
        enabled: true
        storageClass: gp2
    set: []
    valuesFrom: []
  providerConfigRef:
    name: {{ include "aws-default-addons.fullname" . }}