{{ if .Values.apiGateway.tyk.enabled }}
apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: {{ include "aws-default-addons.fullname" . }}-tyk
  labels:
    {{- include "aws-default-addons.labels" . | nindent 4 }}
spec:
  rollbackLimit: 99
  forProvider:
    chart:
      name: tyk-headless
      repository: https://helm.tyk.io/public/helm/charts/
      version: 0.9.3
    namespace: tyk
#   skipCreateNamespace: true
#   wait: true
    values: 
      gateway:
        # The hostname to bind the Gateway to.
        hostName: tyk-gw.{{ .Values.domain }}
        kind: DaemonSet
        replicaCount: 1
        ingress:
          enabled: true
          annotations: 
            kubernetes.io/ingress.class: nginx
          path: /
          hosts:
          - tyk-gw.{{ .Values.domain }}
    set: []
    valuesFrom: []
  providerConfigRef:
    name: {{ include "aws-default-addons.fullname" . }}
{{ end }}