apiVersion: iam.aws.crossplane.io/v1beta1
kind: Policy
metadata:
  name: {{ include "aws-default-addons.fullname" . }}-pipeline-ecr
  labels:
    {{- include "aws-default-addons.labels" . | nindent 4 }}
spec:
  forProvider:
    name: {{ include "aws-default-addons.fullname" . }}-pipeline-ecr
    description: "IAM Policy that allow ECR Acces - is used by pipeline assumed role to creata pull and push images"
    document: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action":"ecr:*",
            "Resource": "*"
          }
        ]
      }
  deletionPolicy: Delete
  providerConfigRef:
    name: {{ include "aws-default-addons.fullname" . }}