apiVersion: identity.aws.crossplane.io/v1alpha1
kind: IAMPolicy
metadata:
  name: {{ include "aws-default-addons.fullname" . }}-cluster-autoscaler
  labels:
    {{- include "aws-default-addons.labels" . | nindent 4 }}
spec:
  forProvider:
    name: {{ include "aws-default-addons.fullname" . }}-cluster-autoscaler
    description: "IAM Policy for Cluster AutoScale"
    document: |-
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": [
                "autoscaling:DescribeAutoScalingGroups",
                "autoscaling:DescribeAutoScalingInstances",
                "autoscaling:DescribeLaunchConfigurations",
                "autoscaling:DescribeTags",
                "autoscaling:SetDesiredCapacity",
                "autoscaling:TerminateInstanceInAutoScalingGroup"
            ],
            "Resource": "*"
          }
        ]
      }
  deletionPolicy: Delete
  providerConfigRef:
    name: {{ include "aws-default-addons.fullname" . }}