apiVersion: iam.aws.crossplane.io/v1beta1
kind: Policy
metadata:
  name: {{ include "aws-default-addons.fullname" . }}-ebs-csi
  labels:
    {{- include "aws-default-addons.labels" . | nindent 4 }}
spec:
  forProvider:
    name: {{ include "aws-default-addons.fullname" . }}-ebs-csi
    description: "IAM Policy for EBS CSI"
    document: |-
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Action": [
              "ec2:AttachVolume",
              "ec2:CreateSnapshot",
              "ec2:CreateTags",
              "ec2:CreateVolume",
              "ec2:DeleteSnapshot",
              "ec2:DeleteTags",
              "ec2:DeleteVolume",
              "ec2:DescribeAvailabilityZones",
              "ec2:DescribeInstances",
              "ec2:DescribeSnapshots",
              "ec2:DescribeTags",
              "ec2:DescribeVolumes",
              "ec2:DescribeVolumesModifications",
              "ec2:DetachVolume",
              "ec2:ModifyVolume"
            ],
            "Effect": "Allow",
            "Resource": "*"
          }
        ]
      }
  deletionPolicy: Delete
  providerConfigRef:
    name: {{ include "aws-default-addons.fullname" . }}