apiVersion: iam.aws.crossplane.io/v1beta1
kind: Role
metadata:
  name: {{ include "aws-default-addons.fullname" . }}-cluster-autoscaler
  labels:
    {{- include "aws-default-addons.labels" . | nindent 4 }}
spec:
  forProvider:
    description: "IAM Role for Cluster Autoscaler on {{ include "aws-default-addons.fullname" . }} cluster"
    assumeRolePolicyDocument: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
              "Federated": [
                "arn:aws:iam::{{ .Values.accountID }}:oidc-provider/{{ .Values.openIDConnectProviderURL | trimPrefix "https://" }}"
              ]
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
              "StringLike": {
                "{{ .Values.openIDConnectProviderURL | trimPrefix "https://" }}:sub": "system:serviceaccount:kube-system:*-cluster-autoscaler"
              }
            }
          }
        ]
      }
    tags: []
  deletionPolicy: Delete
  providerConfigRef:
    name: {{ include "aws-default-addons.fullname" . }}
  