apiVersion: identity.aws.crossplane.io/v1beta1
kind: IAMRole
metadata:
  name: {{ include "aws-default-addons.fullname" . }}-ebs-csi
  labels:
    {{- include "aws-default-addons.labels" . | nindent 4 }}
spec:
  forProvider:
    description: "IAM Role for EBS CSI on {{ include "aws-default-addons.fullname" . }} cluster"
    assumeRolePolicyDocument: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
              "Federated": [
                "arn:aws:iam::{{ .Values.accountID }}:oidc-provider/{{ .Values.openIDConnectProviderURL | trimPrefix "https://" }}"
              ]
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
              "StringEquals": {
                "{{ .Values.openIDConnectProviderURL | trimPrefix "https://" }}:sub": [
                  "system:serviceaccount:kube-system:ebs-csi-controller-sa",
                  "system:serviceaccount:kube-system:ebs-csi-node-sa",
                  "system:serviceaccount:kube-system:ebs-snapshot-controller"
                ]
              }
            }
          }
        ]
      }
    tags: []
  deletionPolicy: Delete
  providerConfigRef:
    name: {{ include "aws-default-addons.fullname" . }}
  