apiVersion: identity.aws.crossplane.io/v1beta1
kind: IAMRole
metadata:
  name: {{ include "aws-default-addons.fullname" . }}-external-dns
  labels:
    {{- include "aws-default-addons.labels" . | nindent 4 }}
spec:
  forProvider:
    description: "IAM Role for External DNS on {{ include "aws-default-addons.fullname" . }} cluster"
    assumeRolePolicyDocument: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Sid": "",
            "Effect": "Allow",
            "Principal": {
              "Federated": [
                "{{ .Values.openIDConnectProviderARN }}"
              ]
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
              "StringEquals": {
                "{{ .Values.openIDConnectProviderURL | trimSuffix "https://" }}:aud": "sts.amazonaws.com",
                "{{ .Values.openIDConnectProviderURL | trimSuffix "https://" }}:sub": "system:serviceaccount:external-dns:*external-dns*"
              }
            }
          }
        ]
      }
    tags: []
  deletionPolicy: Delete
  providerConfigRef:
    name: {{ include "aws-default-addons.fullname" . }}
  