apiVersion: helm.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: {{ include "aws-default-addons.fullname" . }}
  annotations:
    helm.sh/hook: "pre-install"
    helm.sh/hook-weight: "-1"
  labels:
    {{- include "aws-default-addons.fullname" . | nindent 4 }}
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      key: kubeconfig
      name: {{ .Values.environmentName }}-conn