apiVersion: identity.aws.crossplane.io/v1beta1
kind: IAMRolePolicyAttachment
metadata:
  name: {{ include "aws-k8s-stack.fullname" . }}-eks-cni
  labels:
    {{- include "aws-k8s-stack.labels" . | nindent 4 }}
spec:
  forProvider:
    policyArn: arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
    roleNameRef:
      name: {{ include "aws-k8s-stack.fullname" . }}-node
  deletionPolicy: Delete
  providerConfigRef:
    name: {{ include "aws-k8s-stack.fullname" . }}