apiVersion: iam.aws.crossplane.io/v1beta1
kind: Role
metadata:
  name: {{ include "aws-k8s-stack.fullname" . }}-eks
  labels:
    {{- include "aws-k8s-stack.labels" . | nindent 4 }}
spec:
  forProvider:
    description: "IAM ROLE EKS for {{ include "aws-k8s-stack.fullname" . }} cluster"
    maxSessionDuration: 3600
    assumeRolePolicyDocument: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
            "Service": [
              "eks.amazonaws.com"
              ]
            },
            "Action": "sts:AssumeRole"
          }
        ]
      }
    tags: 
      {{- toYaml .Values.defaultTags | nindent 6 }}
  deletionPolicy: Delete
  providerConfigRef:
    name: {{ include "aws-k8s-stack.fullname" . }}