apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aws-k8s-stack.fullname" . }}
  namespace: crossplane-system
  annotations:
    helm.sh/hook: "pre-install"
    helm.sh/hook-weight: "-2"
  labels:
    {{- include "aws-k8s-stack.labels" . | nindent 4 }}
data:
  creds: {{ .Values.creds | b64enc }}