apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: {{ include "aws-k8s-stack.fullname" . }}
  annotations:
    helm.sh/hook: "pre-install"
    helm.sh/hook-weight: "-1"
  labels:
    {{- include "aws-k8s-stack.labels" . | nindent 4 }}
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: {{ include "aws-k8s-stack.fullname" . }}
      key: creds