# Default values for aws-default-addons.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

environmentName: &environmentName aws-k8s-stack
nameOverride: *environmentName
accountID: XXXXXXXXXX
openIDConnectProviderURL: https://oidc.eks.region.amazonaws.com/id/XXXXXXXXXXXXXX
domain: test.domain.com
region: us-east-1

monitoring:
  enabled: true