# Default values for aws-default-addons.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

environmentName: &environmentName aws-k8s-stack
nameOverride: *environmentName
accountID: XXXXXXXXXX
openIDConnectProviderURL: https://oidc.eks.region.amazonaws.com/id/XXXXXXXXXXXXXX
domain: test.domain.com
region: us-east-1

monitoring:
  enabled: true

# NOTE: "gp2" already exists by default
ebs:
- name: gp3
  parameters:
    type: gp3
    csi.storage.k8s.io/fstype: ext4
- name: high-iops-ssd
  parameters:
    type: io1
    iopsPerGB: "50"
    csi.storage.k8s.io/fstype: ext4
- name: medium-iops-ssd
  parameters:
    type: io1
    iopsPerGB: "25"
    csi.storage.k8s.io/fstype: ext4
- name: throughput
  parameters:
    type: st1
    csi.storage.k8s.io/fstype: ext4
- name: cold-storage
  parameters:
    type: sc1
    csi.storage.k8s.io/fstype: ext4
