# Default values for k8s-stack.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- default name used to compose components and environment name
nameOverride: ""
# -- default name used to compose components and environment name
fullnameOverride: ""

# -- content of creds file, for more information [access here](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html#cli-configure-files-where)
creds: |
  [default]
  aws_access_key_id=XXXXXXXXX
  aws_secret_access_key=XXXXXXXXXXXXXXXXXXXXXXXXXXX

# -- region where the infrastructure will be created
region: us-east-2

# -- default tags list for all resources with "key" and "value" format
defaultTags: []

vpc:
  # -- CIDR block for VPC
  cidrBlock: 10.0.0.0/16
  # -- enable DNS suppoprt
  enableDnsSupport: true
  # -- enable DNS host suppoprt
  enableDnsHostNames: true
  # -- intance tenancy
  instanceTenancy: default
  # -- default tags for VPC
  tags: []

subnet:
  # -- list of az with "name" and "cidrBlock" 
  az: 
  - name: "a"
    cidrBlock: 10.0.0.0/24
  - name: "b"
    cidrBlock: 10.0.1.0/24
  - name: "c"
    cidrBlock: 10.0.2.0/24
  # -- map public IP on launch
  mapPublicIPOnLaunch: true

eks:
  # -- EKS version, for more information [access here](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html)
  version: "1.21"
  resourcesVpcConfig:
    endpointPrivateAccess: true
    endpointPublicAccess: true
  clusterLogging:
  - enabled: false
    types: ["api", "audit", "authenticator", "controllerManager", "scheduler"]

nodeGroup:
  # -- EKS Node Group version, for more information [access here](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html)
  version: "1.21"
  instanceTypes:
  - t3a.large
  scalingConfig:
    desiredSize: 2
    maxSize: 3
    minSize: 2

route53:
  enabled: false
  domain: test.domain.com

securityGroup:
  enabled: false